project:
  type: book
  output-dir: docs

python:
  version: C:/Users/m_tai/anaconda3/python.exe

book:
  title: "Introdução à R e Python"
  author: "Magno Severino"
  date: "03/22/2026" # "03/03/2024"
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: Aprendendo R
      chapters: 
        - 01-fundamentos_r.qmd
        - 02-fluxos.qmd
        - 03-dados.qmd
        - 04-visualizacao.qmd
    - part: Aprendendo Python
      chapters:
        - 05-fundamentos_python.qmd
        - 06-visualizacao_python.qmd
    #- part: Prova Final
    #  chapters:
    #    - 07-prova.qmd
    - part: Estudo de casos
      chapters:
        - 07-casos.qmd
    - 10-solucoes_exercicios.qmd
    - references.qmd

crossref:
  custom:
    - kind: float
      key: exr
      reference-prefix: "Exercício"
      latex-env: example

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{tcolorbox}
        \tcbuselibrary{skins, breakable}

        \newtcolorbox{example}{
          colback=blue!5,
          colframe=blue!50,
          boxrule=0.8pt,
          arc=2pt,
          breakable
        }

editor: source

lang: pt    